import{randomUUID}from"node:crypto";import{runner}from"node-pg-migrate";import{Client}from"pg";import{afterAll,beforeAll,describe,expect,it}from"vitest"
const url=process.env.DATABASE_URL!;const schema=`api_test_${randomUUID().replaceAll("-","")}`;let admin:Client
beforeAll(async()=>{process.env.DATABASE_SCHEMA=schema;process.env.PUBLIC_SIGNUP_ENABLED="true";admin=new Client({connectionString:url});await admin.connect();await runner({databaseUrl:url,direction:"up",dir:"migrations",migrationsTable:"migrations_eblon_bibliotheque",migrationsSchema:schema,createMigrationsSchema:true,schema:[schema],createSchema:true,checkOrder:true,log:()=>{}})})
afterAll(async()=>{const attendu=`api_test_${schema.slice(9)}`;if(schema!==attendu)throw new Error("Schéma de test invalide");await admin.query(`DROP SCHEMA "${schema}" CASCADE`);await admin.end();delete process.env.DATABASE_SCHEMA})
describe.sequential("API métier PostgreSQL isolée",()=>{
 let matiere:string,niveau:string,ouvrage:string,exemplaire:string,emprunteur:string,agent:string
 it("crée les référentiels, recherche et pagine",async()=>{const s=await import("@/lib/services/ressources");matiere=(await s.creer("matieres",{code:"API-MATH",nom:"Mathématiques API"})).id;niveau=(await s.creer("niveaux_scolaires",{code:"API-3E",nom:"3e"})).id;await expect(s.creer("matieres",{code:"API-MATH",nom:"Doublon"})).rejects.toMatchObject({code:"23505"});const r=await s.listerRessources("matieres",{page:1,limite:10,recherche:"API-MATH",ordre:"asc"},new URLSearchParams());expect(r.total).toBe(1)})
 it("crée ouvrage, exemplaire, emprunteur et agent",async()=>{const s=await import("@/lib/services/ressources");ouvrage=(await s.creer("ouvrages",{titre:"Ouvrage API",matiere_id:matiere,niveau_scolaire_id:niveau,type_ouvrage_id:"25000000-0000-4000-8000-000000000008"})).id;exemplaire=(await s.creer("exemplaires",{ouvrage_id:ouvrage,code_inventaire:"API-EX-1",statut:"DISPONIBLE"})).id;emprunteur=(await s.creer("emprunteurs",{numero_emprunteur:"API-E-1",prenom:"Awa",nom:"Test"})).id;agent=(await s.creer("agents",{prenom:"Agent",nom:"Test",email:"api-agent@example.invalid",role:"BIBLIOTHECAIRE"})).id;expect(exemplaire).toBeTruthy()})
 it("crée un emprunt, change l'exemplaire et journalise",async()=>{const s=await import("@/lib/services/emprunts");const e=await s.creerEmprunt({exemplaire_id:exemplaire,emprunteur_id:emprunteur,agent_preteur_id:agent,date_echeance:new Date(Date.now()+86400000).toISOString()});expect(e.statut).toBe("ACTIF");expect((await admin.query(`SELECT statut FROM "${schema}".exemplaires WHERE id=$1`,[exemplaire])).rows[0].statut).toBe("EMPRUNTE");expect((await s.evenementsEmprunt(e.id))[0].type_evenement).toBe("CREE");await expect(s.creerEmprunt({exemplaire_id:exemplaire,emprunteur_id:emprunteur,agent_preteur_id:agent,date_echeance:new Date(Date.now()+86400000).toISOString()})).rejects.toMatchObject({code:"EXEMPLAIRE_INDISPONIBLE"});await s.prolongerEmprunt(e.id,new Date(Date.now()+172800000).toISOString(),agent);await s.changerEtatEmprunt(e.id,"RETARD",agent);const retour=await s.retournerEmprunt(e.id,{agent_recepteur_id:agent,etat_retour:"NORMAL"});expect(retour.statut).toBe("RETOURNE");expect((await admin.query(`SELECT statut FROM "${schema}".exemplaires WHERE id=$1`,[exemplaire])).rows[0].statut).toBe("DISPONIBLE")})
 it("refuse un emprunteur suspendu et rollback toute la transaction",async()=>{const s=await import("@/lib/services/emprunts");await admin.query(`UPDATE "${schema}".emprunteurs SET statut='SUSPENDU' WHERE id=$1`,[emprunteur]);const avant=(await admin.query(`SELECT count(*)::int n FROM "${schema}".emprunts`)).rows[0].n;await expect(s.creerEmprunt({exemplaire_id:exemplaire,emprunteur_id:emprunteur,agent_preteur_id:agent,date_echeance:new Date(Date.now()+86400000).toISOString()})).rejects.toMatchObject({code:"EMPRUNTEUR_INACTIF"});expect((await admin.query(`SELECT count(*)::int n FROM "${schema}".emprunts`)).rows[0].n).toBe(avant)})
 it("gère perte et annulation",async()=>{const s=await import("@/lib/services/emprunts");await admin.query(`UPDATE "${schema}".emprunteurs SET statut='ACTIF' WHERE id=$1`,[emprunteur]);for(const action of ["PERTE","ANNULATION"] as const){await admin.query(`UPDATE "${schema}".exemplaires SET statut='DISPONIBLE' WHERE id=$1`,[exemplaire]);const e=await s.creerEmprunt({exemplaire_id:exemplaire,emprunteur_id:emprunteur,agent_preteur_id:agent,date_echeance:new Date(Date.now()+86400000).toISOString()});expect((await s.changerEtatEmprunt(e.id,action,agent)).statut).toBe(action==="PERTE"?"PERDU":"ANNULE")}})
 it("n'écrit rien dans public",async()=>{expect((await admin.query(`SELECT table_name FROM information_schema.tables WHERE table_schema='public' AND table_name IN ('matieres','emprunts')`)).rows).toEqual([])})
 it("inscrit les élèves sans créer de profil agent quand le bootstrap existe",async()=>{const{auth}=await import("@/lib/auth");const premier=await auth.api.signUpEmail({returnHeaders:true,body:{name:"Alice Élève",email:"alice.api@example.invalid",password:"MotDePasse-Test-2026!"}});const cookies=premier.headers.getSetCookie();expect(cookies.some((v)=>v.includes("session"))).toBe(true);const cookie=cookies.map((v)=>v.split(";",1)[0]).join("; ");const session=await auth.api.getSession({headers:new Headers({cookie})});expect(session?.user.email).toBe("alice.api@example.invalid");const alice=(await admin.query(`SELECT statut,identifiant_auth_externe FROM "${schema}".emprunteurs WHERE email=$1`,["alice.api@example.invalid"])).rows[0];expect(alice.statut).toBe("EN_ATTENTE");expect(alice.identifiant_auth_externe).toBe(session?.user.id);await auth.api.signUpEmail({body:{name:"Louis Élève",email:"louis.api@example.invalid",password:"MotDePasse-Test-2026!"}});const louis=(await admin.query(`SELECT statut,identifiant_auth_externe FROM "${schema}".emprunteurs WHERE email=$1`,["louis.api@example.invalid"])).rows[0];expect(louis.statut).toBe("EN_ATTENTE");expect(louis.identifiant_auth_externe).toBeTruthy();expect((await admin.query(`SELECT count(*)::int n FROM "${schema}".agents WHERE email IN ($1,$2)`,["alice.api@example.invalid","louis.api@example.invalid"])).rows[0].n).toBe(0);await expect(auth.api.signUpEmail({body:{name:"Doublon",email:"alice.api@example.invalid",password:"MotDePasse-Test-2026!"}})).rejects.toBeTruthy()})
})
