"use client"
import { useState } from "react"
import { useRouter } from "next/navigation"
import { authClient } from "@/lib/auth-client"
import { completerInscriptionEleve } from "@/app/actions/parcours-auth"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
export function InscriptionEleveForm({niveaux}:{niveaux:{id:string;nom:string}[]}){const router=useRouter();const[pending,setPending]=useState(false);const[erreur,setErreur]=useState("");async function action(fd:FormData){setPending(true);setErreur("");const nomComplet=`${fd.get("prenom")} ${fd.get("nom")}`.trim(),email=String(fd.get("email")),password=String(fd.get("password"));const r=await authClient.signUp.email({name:nomComplet,email,password});if(r.error){setErreur(r.error.message??"Inscription impossible.");setPending(false);return}const profil=await completerInscriptionEleve({niveau_scolaire_id:String(fd.get("niveau_scolaire_id")),classe:String(fd.get("classe")??""),etablissement:String(fd.get("etablissement")??"")});if(!profil.succes){setErreur(profil.message);setPending(false);return}router.push("/espace-eleve");router.refresh()}return <form action={action} className="grid gap-4 sm:grid-cols-2"><div><Label htmlFor="prenom">Prénom</Label><Input id="prenom" name="prenom" required/></div><div><Label htmlFor="nom">Nom</Label><Input id="nom" name="nom" required/></div><div className="sm:col-span-2"><Label htmlFor="email">Email</Label><Input id="email" name="email" type="email" required autoComplete="email"/></div><div className="sm:col-span-2"><Label htmlFor="password">Mot de passe</Label><Input id="password" name="password" type="password" minLength={8} required autoComplete="new-password"/></div><div><Label htmlFor="niveau_scolaire_id">Niveau scolaire</Label><select id="niveau_scolaire_id" name="niveau_scolaire_id" required className="h-9 w-full rounded-md border bg-transparent px-3">{niveaux.map(n=><option key={n.id} value={n.id}>{n.nom}</option>)}</select></div><div><Label htmlFor="classe">Classe</Label><Input id="classe" name="classe"/></div><div className="sm:col-span-2"><Label htmlFor="etablissement">Établissement</Label><Input id="etablissement" name="etablissement"/></div>{erreur&&<p role="alert" className="text-sm text-destructive sm:col-span-2">{erreur}</p>}<Button type="submit" disabled={pending} className="sm:col-span-2">{pending?"Inscription…":"Créer mon compte élève"}</Button></form>}
